# Generated by Django 5.2.12 on 2026-05-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temperature", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temp",
            name="current_temp",
            field=models.FloatField(
                blank=True, help_text="Temperature Celsius", null=True
            ),
        ),
        migrations.AlterField(
            model_name="temp",
            name="status_critical",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
