# Generated by Django 5.2.12 on 2026-04-28 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "SystemPC",
                    models.CharField(
                        blank=True, help_text="Система пк", max_length=100, null=True
                    ),
                ),
                (
                    "Local_Name_PC",
                    models.CharField(
                        blank=True,
                        help_text="Локальное имя пк",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
