# Generated by Django 5.2.12 on 2026-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "SystemPC",
                    models.CharField(
                        blank=True, help_text="Система пк", max_length=100, null=True
                    ),
                ),
                (
                    "Local_Name_PC",
                    models.CharField(
                        blank=True,
                        help_text="Локальное имя пк",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "MAX_CPU_CORES",
                    models.CharField(
                        blank=True,
                        help_text="Максимальное количество ядер CPU",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "MAX_CPU_THREADS",
                    models.CharField(
                        blank=True,
                        help_text="Максимальное количество потоков CPU",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("CPU_NAME", models.CharField(blank=True, max_length=255, null=True)),
                ("MAX_RAM", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "RAM_CHARACTERISTICS",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "MAX_GPU_THREADS",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("GPU_NAME", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "GPU_SIZE_GB",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "MAX_SWAP",
                    models.CharField(
                        blank=True,
                        help_text="Максимальный объем SWAP памяти",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "MAX_DISK",
                    models.CharField(
                        blank=True,
                        help_text="Максимальный объем дискового пространства",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("DISK_NAME", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
