# Generated by Django 5.2.12 on 2026-04-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="CPU_NAME",
        ),
        migrations.RemoveField(
            model_name="server",
            name="DISK_NAME",
        ),
        migrations.RemoveField(
            model_name="server",
            name="MAX_CPU_CORES",
        ),
        migrations.RemoveField(
            model_name="server",
            name="MAX_CPU_THREADS",
        ),
        migrations.RemoveField(
            model_name="server",
            name="MAX_DISK",
        ),
        migrations.RemoveField(
            model_name="server",
            name="MAX_RAM",
        ),
        migrations.RemoveField(
            model_name="server",
            name="MAX_SWAP",
        ),
        migrations.RemoveField(
            model_name="server",
            name="RAM_CHARACTERISTICS",
        ),
    ]
