# Generated by Django 5.2.12 on 2026-05-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
