# Generated by Django 5.2.12 on 2026-04-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_remove_server_cpu_name_remove_server_disk_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="GPU_NAME",
        ),
        migrations.RemoveField(
            model_name="server",
            name="GPU_SIZE_GB",
        ),
        migrations.RemoveField(
            model_name="server",
            name="MAX_GPU_THREADS",
        ),
    ]
