# Generated by Django 5.2.12 on 2026-04-23 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_remove_server_gpu_name_remove_server_gpu_size_gb_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="id",
        ),
        migrations.AddField(
            model_name="server",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
