# Generated by Django 5.2.12 on 2026-04-22 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Use_Cpu",
                    models.IntegerField(blank=True, help_text="CPU(%)", null=True),
                ),
                (
                    "Use_Ram",
                    models.IntegerField(blank=True, help_text="RAM(%)", null=True),
                ),
                (
                    "Use_Swap",
                    models.IntegerField(blank=True, help_text="SWAP", null=True),
                ),
                (
                    "IO",
                    models.FloatField(
                        blank=True, help_text="Input/Output(%)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.server",
                    ),
                ),
            ],
        ),
    ]
