# Generated by Django 5.2.12 on 2026-05-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metric", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverstat",
            name="IO",
            field=models.FloatField(help_text="Input/Output(%)"),
        ),
        migrations.AlterField(
            model_name="serverstat",
            name="Use_Cpu",
            field=models.IntegerField(help_text="CPU(%)"),
        ),
        migrations.AlterField(
            model_name="serverstat",
            name="Use_Ram",
            field=models.IntegerField(help_text="RAM(%)"),
        ),
        migrations.AlterField(
            model_name="serverstat",
            name="Use_Swap",
            field=models.IntegerField(help_text="SWAP"),
        ),
    ]
