# Generated by Django 5.2.12 on 2026-05-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metric", "0002_alter_serverstat_io_alter_serverstat_use_cpu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serverstat",
            name="IO",
        ),
    ]
