# Generated by Django 5.2.12 on 2026-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metric", "0003_remove_serverstat_io"),
        ("server", "0002_server_is_active"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="serverstat",
            constraint=models.UniqueConstraint(
                fields=("server", "created_at"), name="unique_server_stat"
            ),
        ),
    ]
