# Generated by Django 5.2.12 on 2026-05-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metric", "0004_serverstat_unique_server_stat"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverstat",
            name="Bytes_total_recv",
            field=models.BigIntegerField(
                default=0,
                help_text="Количесво пакетов в байтах, полученных сервером(bytes)",
            ),
        ),
        migrations.AddField(
            model_name="serverstat",
            name="Bytes_total_sent",
            field=models.BigIntegerField(
                default=0,
                help_text="Количесво пакетов в байтах, отправленных сервером(bytes)",
            ),
        ),
        migrations.AddField(
            model_name="serverstat",
            name="Eth_recv",
            field=models.BigIntegerField(
                default=0, help_text="скорость интернета(получено)(bytes)"
            ),
        ),
        migrations.AddField(
            model_name="serverstat",
            name="Eth_sent",
            field=models.BigIntegerField(
                default=0, help_text="скорость интернета(отправлено)(bytes)"
            ),
        ),
    ]
