# Generated by Django 5.2.12 on 2026-05-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metric", "0005_serverstat_bytes_total_recv_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serverstat",
            name="Bytes_total_recv",
        ),
        migrations.RemoveField(
            model_name="serverstat",
            name="Bytes_total_sent",
        ),
        migrations.RemoveField(
            model_name="serverstat",
            name="Eth_recv",
        ),
        migrations.RemoveField(
            model_name="serverstat",
            name="Eth_sent",
        ),
    ]
