# Generated by Django 5.2.12 on 2026-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metric", "0006_remove_serverstat_bytes_total_recv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverstat",
            name="Procent_Ram",
            field=models.FloatField(blank=True, help_text="Procent RAM(%)", null=True),
        ),
    ]
