# Generated by Django 5.2.12 on 2026-05-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("server", "0002_server_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeedEth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Eth_sent",
                    models.BigIntegerField(
                        default=0, help_text="скорость интернета(отправлено)(bytes)"
                    ),
                ),
                (
                    "Eth_recv",
                    models.BigIntegerField(
                        default=0, help_text="скорость интернета(получено)(bytes)"
                    ),
                ),
                (
                    "Bytes_total_sent",
                    models.BigIntegerField(
                        default=0,
                        help_text="Количесво пакетов в байтах, отправленных сервером(bytes)",
                    ),
                ),
                (
                    "Bytes_total_recv",
                    models.BigIntegerField(
                        default=0,
                        help_text="Количесво пакетов в байтах, полученных сервером(bytes)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.server",
                    ),
                ),
            ],
        ),
    ]
