# Generated by Django 5.2.12 on 2026-06-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speed_eth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speedeth",
            name="Interface_name",
            field=models.CharField(
                default="", help_text="Название сетевого интерфейса", max_length=255
            ),
        ),
    ]
