# Generated by Django 5.2.12 on 2026-04-22 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SSHLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("success", "Успешный вход"),
                            ("failed", "Неудачная попытка"),
                        ],
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("raw_log", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="sshlog_sshl_timesta_1bdb2e_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="sshlog_sshl_ip_addr_38b7d7_idx"
                    ),
                    models.Index(
                        fields=["username"], name="sshlog_sshl_usernam_c628cb_idx"
                    ),
                ],
            },
        ),
    ]
