# Generated by Django 5.2.12 on 2026-04-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sshlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sshlogentry",
            name="UuidServer",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
