# Generated by Django 6.0.4 on 2026-04-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0004_list_ssh_rename_cpu_server_cpu_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='Local_Name_PC',
            field=models.CharField(blank=True, help_text='Локальное имя пк', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='Name_Processor',
            field=models.CharField(blank=True, help_text='Название процессора', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='SystemPC',
            field=models.CharField(blank=True, help_text='Система пк', max_length=100, null=True),
        ),
    ]
