# Generated by Django 6.0.4 on 2026-04-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0005_server_local_name_pc_server_name_processor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='Name_Processor',
        ),
    ]
