# Generated by Django 5.2.12 on 2026-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Htop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.IntegerField()),
                ("proccess_name", models.CharField(max_length=255)),
                ("cpu_usage", models.FloatField()),
                ("UuidServer", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-cpu_usage"],
                "indexes": [
                    models.Index(
                        fields=["UuidServer", "created_at"],
                        name="htop_htop_UuidSer_7c9b4f_idx",
                    ),
                    models.Index(
                        fields=["proccess_name"], name="htop_htop_procces_ed8f02_idx"
                    ),
                    models.Index(fields=["pid"], name="htop_htop_pid_e5244b_idx"),
                ],
            },
        ),
    ]
