# Generated by Django 5.2.12 on 2026-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ram", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ram",
            name="RAM_CHARACTERISTICS",
        ),
        migrations.AlterField(
            model_name="ram",
            name="UuidServer",
            field=models.CharField(max_length=255),
        ),
    ]
