# Generated by Django 5.2.12 on 2026-05-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ram", "0002_remove_ram_ram_characteristics_alter_ram_uuidserver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ram",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
