# Generated by Django 5.2.12 on 2026-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disk",
            name="Free_DISK",
            field=models.CharField(
                blank=True,
                help_text="Свободное дисковое пространство",
                max_length=255,
                null=True,
            ),
        ),
    ]
