# Generated by Django 5.2.12 on 2026-04-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disk",
            name="UuidServer",
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
