# Generated by Django 5.2.12 on 2026-04-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="gpu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MAX_GPU_THREADS",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("GPU_NAME", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "GPU_SIZE_GB",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
