# Generated by Django 5.2.12 on 2026-05-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpu",
            name="UuidServer",
            field=models.UUIDField(unique=True),
        ),
    ]
