# Generated by Django 5.2.12 on 2026-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpu", "0002_alter_gpu_uuidserver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpu",
            name="UuidServer",
            field=models.UUIDField(),
        ),
    ]
