# Generated by Django 6.0.4 on 2026-04-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metric', '0002_serverstat_cpu_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverstat',
            name='Cpu_Info',
        ),
        migrations.RemoveField(
            model_name='serverstat',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='serverstat',
            name='ram',
        ),
        migrations.AddField(
            model_name='serverstat',
            name='Use_Cpu',
            field=models.FloatField(blank=True, help_text='CPU(%)', null=True),
        ),
        migrations.AddField(
            model_name='serverstat',
            name='Use_Ram',
            field=models.FloatField(blank=True, help_text='RAM(%)', null=True),
        ),
        migrations.AddField(
            model_name='serverstat',
            name='Use_Swap',
            field=models.IntegerField(blank=True, help_text='SWAP', null=True),
        ),
    ]
