# Generated by Django 6.0.4 on 2026-04-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metric', '0003_remove_serverstat_cpu_info_remove_serverstat_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstat',
            name='server',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
