# Generated by Django 6.0.4 on 2026-04-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metric', '0004_alter_serverstat_server'),
        ('Server', '0006_remove_server_name_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstat',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.server'),
        ),
    ]
