# Generated by Django 6.0.4 on 2026-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metric', '0005_alter_serverstat_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstat',
            name='Use_Cpu',
            field=models.IntegerField(blank=True, help_text='CPU(%)', null=True),
        ),
        migrations.AlterField(
            model_name='serverstat',
            name='Use_Ram',
            field=models.IntegerField(blank=True, help_text='RAM(%)', null=True),
        ),
    ]
